export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const INSERT_USER_START = 'INSERT_USER_START'
export const INSERT_USER_SUCCESS = 'INSERT_USER_SUCCESS'
export const INSERT_USER_FAILED = 'INSERT_USER_FAILED'

export const SEARCH_FRIEND_START = 'SEARCH_FRIEND_START'
export const SEARCH_FRIEND_SUCCESS = 'SEARCH_FRIEND_SUCCESS'
export const SEARCH_FRIEND_FAILED = 'SEARCH_FRIEND_FAILED'

export const ADD_FRIEND_START = 'ADD_FRIEND_START'
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS'
export const ADD_FRIEND_FAILED = 'ADD_FRIEND_FAILED'
